services:
  backend:
    build:
      context: .
      dockerfile: infra/docker/backend.Dockerfile
    container_name: ckrafte_table-backend
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      PORT: 8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./shared:/shared

  frontend:
    build:
      context: .
      dockerfile: infra/docker/frontend.Dockerfile
    container_name: ckrafte_table-frontend
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://localhost:8000
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
